// ==UserScript==
// @name         Instagram AutoFollow
// @namespace    http://tampermonkey.net/
// @version      0.20
// @description  try to take over the world!
// @author       You
// @updateURL    https://github.com/randomperson190/usersToFollow/raw/main/usersToFollow.user.js
// @downloadURL  https://github.com/randomperson190/usersToFollow/raw/main/usersToFollow.user.js
// @match        https://www.instagram.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=instagram.com
// @grant        GM_addElement
// @grant        GM_xmlhttpRequest
// ==/UserScript==

function getCurrentURL () {
    return window.location.href;
}

const data = `morecampoy
daiianaa._5
maairepic
maca_cuevass
valeenpalma
cattapereyra
abrilautunno
shaiel__
nikiivega
camiialbarracin_
veroayoroaj
zoesarubi_
luaguiirre_
she.is.lolaa
lourdessolis38
correaacele
magacentteno
melina.boch
briortegga
danaagostinaa
psyccony
agus_surita
sereepesaresi_
agus_berenguel
ludmi_fuentes
_sofi.correa
cande.yanivelli
tomaslorenzoma11037
catluquez
_araa08
braunl_
moreparera_
micaorosco_
milydomiinguez
mmorena.1
niji_romkvzfl
giulygonz
_luu.datri_
naycascone
camii__st
kiruscapina
zoepnzani_
_ceci4
maiochoaizpuro
ilianagrillo
eugeniaszwec_
ayee.tejera
chabeaccossato
azuu.borgna
mayvergara__
abrilrigotto01
checchuu_
_jjazzminn_
vaal.0n
aix.iaraa
daidieci_
_camiiperaltaa
agustinaprette_
iaraa_brahim
melveronn1
juuliherrera_
celesrodriguez._
magui.lucila
alderetebri_
delfiilescano_
_fabiii.10_
mari.llopiz
meloviiedo
melany.rocio2
guadaa_nicole
biangiovannini
vicky__gimenez0
_mariaperalta_
delfina.villegas
bustosmily.2
isaa_marrone
melalmiron1
tamiichavezzz
gnerikaa
lugonzaaleez
micahernandezl
sofirodrriguez
aleesspinosa
leidipa__
nickytorrado
agustina.arayaa
coniii.caro
zooe.a_
ani_ruizz
samiracardosso
ailuu.tt
roobelenn1
fatulina
vikysanfe_
luci_.torres
zelmigarcia
antto_montenegro
martuu_olmos15
lunimara_
antoomarquez__
milidominguez16
vicky.zacco
ailynmilagros_
_guadagaitan
zoedelrioo
martu_pardo
martineezmili_
giiulialvarez
rooc1o
delfizela
_rociooabigail
guadasisa
guadimontero__
patopatoyrepato
suritamel
piafelicetti_
aye_aguss
luliipalacios.37
ssofitorres1
ludmiisegura
mileebobbio
caro.caastillo
_mmilagross_
agushalbr
mel_m.aredes
luuz.vict
camibbeleen
ariiiaaa
fl__orce
biancamagaali
cariiamaro
zoeecattaneo
milii_aylenn
lucilamagali00
_soyathina_
zairaluquez_
viaany_ema
camilaespinosa09
more.corzini
abrilcorreaw
villalbacande__
solvbarbozaa
caroyeruna
ayelenlucero_
pilidiazp_
florfranzese
brisaailennn_
laaramacieel
miaa.alfonso
abalosari
mendezzbri
jazcarnevale
camichiappara_
may.zela_
tutii.gutierrez
jazduarte__
abrilcorreaw2
miluu.pogonza
brisanaahir
sfelicamm
lal.ilaura
_abbiolivera
mara.ssari
iara_ailiin
juliabriil.12
biaan_ojeda
lei_jimenez
briisa_garay04
jucentofanti
valuu_roman
sofivirg14
lili.melony
delfiarismendi
lulibar________
mmore.lacourt
lulyyaguirre
coronellana
imnotviolo
belu.bertolaa
cami.mendelek
erii_milena
_martualcober_
luuargannaraz
bustsmily
larahaecks
coticirillo
candee.yael
sancfloor
agustina.bre_
albornozailiin
ccamiveiga
soffgilduart7
camii.garciia
miliferrando
daydominguezz
kika.coronel00
luzz_marinaa20
nicolebainotti
kiaxxs
tinagus2005
turron_de_paco_ewe
miilagros.herrera
abriilramos_
danielamoralesuribe
eliicollado
sofiaholmbergfoto
ester_vanesa
mpriscila____
eliana.gauto
mickyfernandez_
donna.carena.92
lulacarelli
bri.luquee
danii_notte
sofiiijalil
garzon.jacq
elisa.massa2402
daianaabregu
daanitta1
daygisellegimenez
valeriabuenosaires
pequee86
sofi_sanso
sabrii654
chavier.gabriela
camferrary
__nahii.benitez.ok__
lucianagabrielarossi
vale3sols
barbarita_bardon
lorealailugones
micaelamorin
manu.giambra
nadiiaa_vaneesaa
vikitarey
casas.marisa
romina9658
any1712
grafnancy
nicolenani
solciito.gonzalez
marchumarchu77
borenatalia
giselagomezz
solcito_150885
gisemosta
maruuu_mat
mamas_171
cecydiaz33
isaa_slt
sofibeatrice_
villagra.kiara_
adri_ocanto
camiicuervoo
magamoreno86
fabianalobbosco
lucianabarrueto
iaramoscardini
cristhal_negro
rodulfoliliana
ccamiailen
melina.bellezaybienestar
isolina_marisel
romivj
ailuuleserre
la_morocha_de_maipu
luanaapinto
luceromaggie
brisaafariass
gabri.santanaa
cinti_cas
rorovera
betyseg
cinrocha1980
carghiardelli
lorenaaaasabrina
tamaradillmannfotografia
camicattaneooo
porrecayanina
simplemente_unica_80
analiabruni
villaresmara
figueroaa_daniela
marilina.cuenca.85
yani.d.ricota
maii_0.9
32_malasuerte
paula.nieva.549
marupal18
marianela.rom
andy.harillo_ah
florenciasofiapozzi
cattainimari
mel_sosx
milislootmans
natalibelenlemos
morcheebaskye
agusymateo
lolaglamqueen
mariagarcia760326
jenif_er5755
luli.cavion
lara.morales_
mica_chiesa
giulimorettoo
flaca_sissi
lizmartinez117
agustargirl
val6nn
fffloor.r
aymicarna
camilapalczi
mileurbancic
agos_saavedra
agusblanco_
chuleonardis
marucencic
candy_orona
candee.la
milivegga
ceci040116
florobless
marcapde237
carolinapenia
cami.dragani
cami.lopreiato
camiisucci
lucia_perri
carolina.landrielg
sofiorrico
pri_cristoferi
agusbibini
flaviavallejos_
raquedasilvamello
aldanavquiroga
agussromanello
cangarzon
belen.arg5407
jazcpc
agosdaneri
laurataboas
ornescarfo
naiaraveltri
luumanuel
mica_mora98
cereijocami
victoriacarrizo_
meliturria
paauga
julinaveira
sofitatoo
martuacedo_
naaibelen
gimenez_vicxx
agossrdz
leila.salinass
_martirrink
florguutierrez
micaaelaaldana
florcabreraa_
lauriigenna
chiaamangone
juazoulay
daniela.gimenez2
lud_halbich
ipatitu
agu.taquini__
iry.kuz
ivy_garciia
romylalu
_guaaaada
damontcande
mai_lanzillotta
agostinasj
sofiivictorianna
malecocchiola
martisinforiano
_milagr0s._
tiziisigurta
guadaknudsen
julipaez989
a_rlette
chiaraboiani
acostameli_
daigago
tammy_bordon
sofiargenziano
c.e.c.i.i.i
samlovesyoursmile
camiladaianaizzo
florerrecalde
camilaayelenn
cami_venturino
mika_correa
camiddorado
marisasalcedo_1
bianzoppini
ailin.mms
claritaolmos
decimoseptimaletragriega
camspinelli
abrilsko
belen.mjrs
florpalmi
micurambaud
agusss_marquez
sofia_antonellabacas
luugenna1
paulinkaaa_
tweety898
florcirigliano_
marcela.menesesh
sabrinaaylen__
florsuraniti
arianaschmidt_
_cami_caceres
julicastilllo
karen_steinle
style.allison.vii
giuumeza
solcasteluchi_
irisrae15
candelagomez2
shaiel_8a
rooldan_valu10
_sool_villalba
sabasdqt
iampiscis
flora.ac2
ceciarchilla
abrilpastorotti
maru_tu_colo
cata___aguero
sara.pereyra99
mikaaa23vaninetti
deelfi_vip
agus_caviglia123
marii___paganoo_
celi__viipp
val3ntina.m3r3le
ailenn_arj
susi_i40
joii_caastroo
nagodemore
candee.garcc_
pri_cortezzz
bris.a7667
carlagomez5557
tu_rubia_8611
garciaaaa2378
sol.bossi
mary.turnes
tejera_miaa
aldalovepierrepaul
l4ti.ziaguilar
lttt.ina
valenn_caseres78
kaatialoopezz
maii_viipp.15
naiguzzetti.ok
almitttaa_
diame.fava
123_anto_pirola
candevippp_
__clariiii__
azugonzalezb
nahiarocampos
agus_biggi7
martu_godoy__
zaira_vipp
martinagodoy_15
lu_dechiaa
cata.aguilar1
bnlenp
viccobertolini
julietaanderson5
celess_fava
cande_riemer_
beluu_taus
prii_campooss
valen.larreaa
_kaatheee_
more.quinteros12
isaarfarass
emiliitaaaaa_
bere_.gerez
lourdestizio
luu.lezcan0
lunacabral7
ppazjulieta
zahigalvan
valentina.escot
antoo_osorioo
alumine_sosa16
fiore_yanivelli27
sargiotti.oliviaa
priscilapinero_4
beree_agustinaa
aluu_santoro
violetabalinio
la_pilii_paa
jimebianqueri
julianaquinteross
iaraa.tauzz
mica.zarantonello
emi_camargooo
luu_sueldia9
maii.farias
pilisanchezgalarza
britoviole_
paz.maureiraa
angeles_toti
michellepilarr
llanoagos19
ramialvarez78
marti__leguizamon
juana_fatica
la_morelegal98
pili_vrancic
pilibericiartu4
malena.carril14
aguusgonzalezz___
estefiii015
maleeguzman__
tu.more_bb
candebianqueri
azcona_mica
juliimorales1
alvareezz_milii
lucii_badano06
vilaa_agoss
cxlst__11
abixiscari
ddafnesitaa
ferna_n8213
redm.arlox
davinia.leyva_
alwaysmartiiarii
_yadiira._08
naiaracabrera.4_
surkix8
whyaga_
nere_nereita03
ainhoaa_d04
twxiiso
sanncheeezz.2
estefania_lopezz32
julicarreraa_
ornecorrea_
_mmilla03
huilenzufiria
fiifobixio
danu.edgar
luu14.5
ssofiiescolani
camiiicastroo01
chiiinaaa.20
micalopez8573
antonella.saraa
clariisuarez_
antoolvy
maartinezmaga
emiescobarr_
morii.ok_
candee_villagraaa01
florcidiaaz
jazminpecot
miica.anton
oh.soolci
victoria.sandoval5
gonzalezjacke
valen_.saravia
ely.camino
miiia.martinezzz
abru.arias
luliioliveraa
yaazmin.isabella
danigonnzalez_
iglesiassiaraa
pilumones
solchifurlong
valu.romaaan
nahirailen01
floor.chaass
lour__gonzalez
vicky_panno
emaa.pantanali_
melzudaire
luly_yasmin_
jessicamagalii
sofiibarros_
almaamoyano
_celescoronel_
agus_vique_18
tefiifortinera
florencia.belen03
candecheraa
guady_sibione
acosttae
adrielly_leeh
abrilviiidal
sroki_rocio_
martuortizzz
brendarohr
daiana321_
cammila.carrasco
guaadagaleano
seletierno
luuweitzel
briijazz_
agusbcattaneo
prii_jc
sofi.mauas
juulie.ta
melulemos
moreedandrea_
sooarias_
juliifischy
_micc.lopez_
delfiheck
ludmila_belen_01
yazmiin_aylen18
serereber
meli_lunaok
mannuvazquez_
vericresta
canddeavila_
flor_alarconok_
_candelaguirre
nereeaguero
dali_victoria
jovinnik
belucuquejo
tiziiotero_
milagros_malena_
macarenazacarias
aanabell_
jazmaez_
moramatos_
soldanoflor
camiraineri
telmakozz_
maru.poso
martusatera
aylucano_
melinaaibarra
maybustos_
macaarribas3
beelu.coronel
carlagarnero_
arac3lir
cande_duart
glenartegoitia
lara_macarenaa
sofinarella
rociio_reiinoso
cami.donda
vickykogan
morafragano
martugomez00
emmit_a2
yulii.rodas
_floorchavez
lunaportells
lulidominguez3
prioliveer_
victoriia_juarez
fioocorbalan
_bus4n
nicolee.irina
shai_barrientos
rociomonntes
soofi_pannunzio
scorzoflor
mayy_leguizamon
_martiquinteross_
sabrijaime_
maaiabigail
julieta.galeano
candeelaneri
olsoncasandra
candeherber01
breenordas
karenjofre_
nicole.caria
_arigervasoni
ccamianahi
miliiii.23_
lulayatzky
sofifrias
aresosa_
faustiaquino
lucebelenn
_candelaa1
agusm0nzon_
laramonnzon
milaa_cabrera
sarahmoheb
ludmii_paiva
carla_arra
kamcivelli
fxntxsmx_0
martuucoria
micaela.lirola
lourdesostoich
mica.agustiinaa
maylamass_
melperezz011
rocioaylen7
lulii_striker
thiarasuarezz_
mvmelian
abby_r26
bianbrignolo
yasminluly
coni_zieminski
kimcrespillo
valenn_fornaro
ana.villalbaa
florpizzedaz_
analiaeva.15
jazminmiranda.22
cirillolourdes
meliluuu_
maite_2003_
florvaldes14
manonnberl
tamimitriani
roo_barro
jenni__godoy
xpaovelasques
valenmeccia_
agus.aylen05
kia.denisse
mayy_jimenez
renaa_dacosta
_.nicole.56
sofidossantoss
azambuyaabi
martina.med_
miliagostina_
danimagistelo_
canndelud
agoss.romano
valrosselli
_florrr_ok
vaneelial
natyneudeck
valenlauriaa
naiuumor_
aguus_arizzaga
agus_photodumping
caro_copia
jazz_suarezz
zoeortizcano
ludmi_penz
yamxl_
gabrielavelezpsi
anippereyra
milii_cabella
delfii_gg
romi_kannemann
ara_vargass
leticia_pimentel8907
ailinlucilagomez
jimediazz._
luzmazas__
almendrada_
viky.vallejos
milibenavidez_
miiilii_____
miluuu_m
sheilamayares_
sofibellusci
iaruspd
_agusgarbero
agoss.dandrea
luzmilaescobaar
paulaa.grc
brisajimenez_
almi.esquivel_
niky_marye
clueleesss.girl
micaelar0driguez
aylen_flores20
miliaylen26
taay_mf
lali.nieva3
brisapacheco12
chiaracardomin
giulivaldezz
kia3114
delficorboo
fiore.loppez
leona.beautyandwellness
mayra_sagues
luoccelli
caserescamilaaa
julieta_sabrina_galeano
valugonzalezzz__
bbernarditta
noe3749
luli777_sito
__moyano.ok
nadiasosa07
marthanoguera01
rocio_aylenmartinez
delfiiii_lopez__
deniserojass_
caamilagrisel
val.yenzi
solci_schefer
rocio_verduc
miliayelendiaz
martu_echaniz
agustina_scheffer
kimberly.sabrina03
delfi.perichon
leeeeii1
ro_farese
annnarce
beebuu_dee_river
lourdesarias.ok
candee_gonzaleez
lairolon_12
sayago_mar
luubelen7
candelapros_
noee.coriaa
naiara_antonella
micazalazar5_
miilii.acevedo
iara.camila01
abigailcamila0
soff.alg
iara_gomez17
luz_legrini
tamara.aimara
julischmiddt_
agus.yedro
belen__magali
__lu.castro
_may_martinez
maicoroneel
camiivella
brenoyhanarte
venuus1_
loreley.magali
chinaaacid
_soofi_romero_
gaby_gonzalezok
magali.romero_
jay_kumar_1.1
aldanacbustos_
camiiromero0
_maca_alvarez
sandry_aguirre95
melisaradino
__marin__09
kikimimiq
ailu_.04
yoanaargiro
joscelyn_navarese
kiara.menchaca
cris_chenn
nahi.padillaa
f_x_marafiebre
laracuenca_
rocioo__diaz
ls.vernengo.ok
flor.gimmenez
_maleee08_
gonzalezcata__
stefm.a_
_antoo022._
23.cannde
saamy_magali
meliquiroga33
ludmila_baggettaa
_samyy08_
cami_deloma23
giuli_0991
micaelaaa_074
_vazquezflor
jazmin_milena_gomez09
miiluuu_99
_.luzz_15
cande._543
agustina_cacchiarelli
ibisjaraba
belenntrovatto
d4nu.23
yanina_02_09
nayla_alvial
b_nt.a
aguilar32270
n4y.ibarraa
23.ruloo__
candemunoz1_
valenesquiivel
naiu.triv
jime_rocio21
massimiino22
miilagrooss_06
_vvalentinasol
martina06_dlh
casiana_dlb
julieetabustos
veelizz._
valen_torres.02
lourdes.ayeleen
nadelvalle_
priscila_agostina2
kmy.lvv
kontalaaa_comoqieraa
ailin.charrass
x_alma._
miabt_
valengoro_ok
_nareagoss
ddiazmoree
ayelenn.77
_naaaahhii
emilsecantero97
agussliggerini
lolo.lore.1
marinagarcia_._
melody.laura17
04rinaldi_
prisci_gani
martinna.77
madeleine.lopez.16
_nay.cc
kiaraa.antonela
maribel_galarza22
palofaggiano
valen.diaz25
melialvarezzz
danielaortega440
brisa_lunaa3
nicky_aguuuss
wanda_reguerobj
anyii_kiaraa04
paualmad
tiara_abiiigail
nair_sh
xiimena_.priscila
natashabrito04
kiaraa_franco
d.celesstee_
miicaeelaa.01
laruu.luna
ludmimagali22
abigail_agos88
magalilopez.2263
__yamiigonzalez
miluaylenn_
azulacosta77
_cambrooke
iarabelenn
_tatu_10_
magd.alenaonate
carolina.ramirez2411
olivamelisa555
mohibe.20
candee_ook7
brnugarte
araaceli.belen
laurazalazarr
ailu_seg
evee_agustina
jennivera._
nazarodriguez_ok
ailin_kiiaraa
magaa.bustoos
ccandydimarco
micaela_nieto15
aixa_pizarro
leonelasilvani
lu.luramirez_
aguss_gonzaalez
alexa.lo.7121
agustinaatapia
daibarrera0
suzif.bernardo
karenstefania_g
vicoconde
ani.aguero
yam.suarez12
dd.leiva
_abbivivas
kateromeero
melii_810
_marinieto
paula.paezl
gonzaalezzz.01
magali.ailin
iaraperez__
belumarin24
_larilosano
herreramariquena
xiogiimenez
loa6737
maribel.a2
mica_bazan2
nenaquemada_
deise.roupala
flor.britos
meli_gutiaraniz
celestemaribelflores
brenmailen_
genesiscm21
ayelenmanriq95
rocif15
nahee.meza
cry.baby4.21
angeles.bs_
milysandoval___
maguicisneros05_
tequieroperosoyunbardo_ja
arrietaaaju
valentina.barrozoo
miaavelez._
guadalupe.ayelen
tattianaponce
belen.gonzalezz9
azul.a.camargo2
maypaez01
_martineez.p
lamasnombrada_22
priscilaa08_
pamecabrera24
camila.gutierrez.mc
centuludmii
santillanagoss
dani_jht
valee_albiazul
paohiidalgo
noemro
lujanxiomaraa
geneeibanez
yamiladruiz
escuderocindyy
agussmazzeoo
solciiprado
mxra.cxsta_
agusindovino
nataliaserna02
ludmiolivero
bettinaa_abella_chalart
sogosmilena
shamy_francavilla
fernanda.trelles
kiarasalamoniniok
leilatules
pilytaacho
eisamei
paula0016__
katherina.am
ccynthiaaballay
aldi.venvenatt
vell_gxm
anisoraire
_irisponsable
cristacuelloy
orne_buzzi
_rosigodoyy
karencba.199
cotimontivero
silvinafuentes744
brisacandelaa__
soffimoreno__
oriana.abriil_
sofiaylen1_
caropugliese_
brisaherrera._
aguirrbelen
_stella.reynoso_
anahifuentes22
aissa.smith.__
dannielivieira
akitaok
fatimavi9881
guadaaylen__
melina_sosa21
moree._.109
na_yeli8428
celetoledook
valen.benti
florenciavegamolina
nataliadiazkeske
rosario.carrasco6
macab45
veronica.navarro.822
naty_sombra34
yaz_magui
julyortiz17
aguusayelen01
nina33yani
brisa.09
mili.araya04
camiqui___
sofiicoria16
ayetorress_
mariajcepeda09
mara19cariboni
_madeleine__94
ceci140793
ricoteraaa
guimoli.01
__iricoimbra_
yamyabdon
brenda.barzola
tamibarroso29
sosopuebla
luckmannv
danielaavegaa
paugarcia.99
fiorella.toscanelli
aldimercau
ailen2825
damariscarrizo1
emma.requelmee
gris.pina.92
brenda_.marketing
anastasika
sheyhdzflores
brisamonjes_
luciabrondo
yetlanezipao
tamaracadelago
ac_gise
nicol_szkarlat
aldanariemersma
milagros.sanchez2023
naniihsaez
miluuoliva17
brendaa_lopez26
mica_aguero_09
alexandra.gordillo.96
kimeiperezz
abigail.galves_
mayraa_frede
loa_girardi
milii_.sosa
keilacabrerakahl
crucillabel
belen_c32
gyana.ojeda
betianaperinetti
dapecorari
yadia.assat2
lujan_lu99
seleviale20
anto.szkarlat
bel_ssd16
ortiz.silvina
deeboohgomez1
mariapereyra0
ale_lab2904
ayleen_macaa
majogon__
gianinazalazar
katubazan
milagrosparatore
leonela.olmos
sabrinacalderon_
soolmunoz
luzyrastorza
figueroavalentina_
sofipizarro20
jessicarolon2456
carito_singer
eugedominguez.1
sheshi_22
jimenatorres114
rocio.chuky
lourdes.garciaflores.587
celeste.escobar15
luli_isaia
daalbarroso
florencia.lucero.587
julayduval
mica.ruybal
rochigomez16
_yashidalgo
n.nati98
camicolonga2
anto.romero_
brenochoa22
eugeniapoma04
maiarce23
tatii_gramajo
magal.artigas29
mel_godoy97
ana.rosales0
verito_cabanay
gime_pautasso
may_millo
loli.ale29
veriitourquiza
guada.mirandae
loren_grissel
johana.sombra
_melisaleon
alequevedo1
lucy_sosa15
agusluna0597
vilchezz00
mili.ledesma21
abrilrochaaa
_silvii_fz
baguena__belen
yamiiguzmanj
nicole_salinas01
angeles__1143
camilamedaglia1
emiliacollosa
olery.daira
kriss1614
analucianaochoa
micaelaarenass
n.orianaaa
klara_petty_marte
soo.pereyra
rocio.heredia_leon
g.i.m.e.n.a._
bren.ochoa29
soledad.de.nardo
alanizcamila
maakaa_1
ainaragisele.luna
milagrossilva012
joa_aparicio10
karen.s.dominguez
dalmaamoreno
lujan7529
rinabetances_
_agussslopez_
ortizmicaela18
user250395
sofiiaotero
micaela.pereira00
valentinacasale9
viickiii_paratore
_taty.villegas_
lu.norambuena
lula_p28
mili_lucero13
alis_ferreyra
estefyflores05
milagrocastrok
micaelasuarez301
floorcoria7
ortiz_danna22
tiziana.palacio
rominavidela2
lucii_cerutti7
magui.maga07
estefanialucero10
romibazaan
valentinasos_
claudiarominaf
yanetjamier
lucreciavivas
joline206
dominguezjennifer43
yelig09
virginiadominguez_02
yissel0271
solange.herrera.54
milysitjas
estefania6234
aylenxolivera
macameineri
yureidy_perez
estrada_vanesa
maii.moreno.7
micaaa41
giulianarumie
amaya.laura22
poncebeluu
antoolopz
ro.romero96
coria_valentina
candelagesc
anabella.methol
silvibea2
fioreklug
jesidelmolin
mariana._barroso
camilarebca17
nadia.fernandez.184
nicolle.daruich
fercabrera7517
estefania.s_20
marti.na2286
yazminbarcia44
lucero_rocio03
nair_rozale29
bren.caastro
aldanayamila12
leeidyos
janabel16
priscina.batista7
cami_ledezma06
belen.veneciano
_flores_fg
analia_22m
jenn.dibucci
morena.trissia
belufunes.2
esposito.cintia
belen_vangelisti
sofiafebre
sofiaagomez_ok
rbl._.25
agusromero620
a_lazarita
_22ferchu.m
andrearospina
gabiimv18
rossyhcs
_lizi.sanchez
yeni_003_salazar
pameruybal
pa_o_la95
norquelys_alcantara
lakukiloca
sofiariemersma96
poly.montiel
sofiacandelamora
agusbonetto0
luligurmendez
agostina_villarroel
pameicardi
lorenalarapuello
micaa.escudero
ayelenss9
antonellab.k
abril.ruizc3
rojasnadia13
milagrosss_17
adriquinteros
morennamar0
dominguezmar08
karla44segovia
rocigomez39
floordolman16
camila.ochoa9
selee_aguilera00
vanesacastanon_
florencia.escudero2
milividela02
mariel_perez_soto
nadiaguzmanorietaa
mariela.arzac
maruugonzalez19
soyjessterrazas
miliivaz23
meliiquiiroga.93
lissettvaldez17
melina.lucero08
shennyfervidela
nahir_icardi
lourdess.lucero
rocio_105
labarbydelacruz
ariadaro
ro_acarate_917
biianca_ambar
_laabi_
camila.aparicio1
brissabasualdo
yanlizmar
nathalia_vargas21
_carolinabarzola
melissuarez_
aguuspardo
meli.miranda98
viru.torres
gimenez_sabri18
rocio_carranza18
aniiipaujofre
celiambrogio1
tizigomez
yanildagutierrez
maria_sanchez_18n
andreaguilera82
ludmilarsuarez
valee_gonzalez10
luanitavmok
maiigarrooo
sashazapata
ludmilagodoy99
villalonfiore
giulia_salome
sabriimorinico
ibarrarocio809
karito_sipenar
chinibaderr
brisia.svid.22
maria_luz_garcia
melaniehollman7130
vale.gallardo3
fernandez.marianela0
tamara19.97
griser_leger
sol_vilchez27
tamisombra
paulagomez.0
roxi_moreno18
zoloa32gmail.comnatalia
milagrosojeda119
collistter
sofiand96
guadag28_
nanii_guzman022
alexmedya01
valentina_montivero
arimiranda.98
daiana_bonetto
priscilabbarroso
tellomale26
quirogamaar
hola.lu10
florenciapallero15
abi.aguilera11
brenda.rodrigueezz
nmaranguello
carlasosa56
starp.es
melyy_domiinguez
scaypuello
dayanaquiiroga
im.brunette.doll
eugenia.chilano
lauradepa97
la.tati_viip7
zaii.vip222
sami_rodriguez_723
dana.zeballos
lara_barrios_55
agus__.vipp
aguss_08_okk
aimmuchaaa
angyluana9
moree.toloza_
moree_bronicardii
milagrosvargas232
olivello_abby
escobar_valen01
brune.18ok
florenciavz2021
jennii_antuneez
morena_gallastegui2
zoteloday
ttatyyyy_
morebarragan_
aylu_cabrera_
melisabrenda779
cl4udi4_chicl4n4
yam1laa
aylen_cabreraaa
dianasolalarcon
cande_borraz
ro_reinaldi
nataliobregonn
saira_bertolini
tuunatyy
la.ludmiii
luddfunes
melyygonzalez_
aricomen1
iara.denisse
jaaz.corrales
tiary_jara_
iara_fernandezz
celi.ponfe
yaninalaime.35
belen__sandoval13
ta.peraltaa
aymara_leon1
caamiojeda_04
more_donadia
carrizocan
marcejara3
paogonzalez1442
lunabj2003
milagros_avalos_18
mili_romannn
soljazmiin
rociosanchez1232
pao_15_10_
agus_paazz
umaminnella_
rodasaylen
biann.ochoa_
cande_pardo
eve_scola
priscsalva
cuyenbonfiglioo1
can_luna8
cannn_luna
barbaraja5uregui
agus_lavalle
veintidosabi_22
soledad_martina_35
lourdesquiroga.19
agustinagonzalez2171
ayee.burgos22
estefi_sol_
_rocioo.a_
pamela_ayelen_
tina.quintana_
brenda_aguustina
nahiiali
laurapersico_22
carrivalentina
luulii.__
juliietacuevas
pauula_flores
delfyyrosas
chinitta46
maruu_gelp
sole5992
more_wolcan
vanii.centeno
la_luu._.ok
camiiferrao
lara_suarez0
morenoabril087
martu_066
zooe_garaay
roochi__22
toralesgtg
jaaz_wm
d.francia21
juliii_okk25
maguii_https_lol
aylenjazminflores
delfmarr_
aldana_rodriguez29
angie_toribio06
lulii_romero213
agustina.farias.7547
_agustinapereyra_
agustina.ibarra
agustina.cerra
_agusferrero
agus_campora
agustina.sanchezzz
agustinasinfron
bianvillani
agustina.abeti
agus_cater
__agustina98
_milagrosagustinna
agusscascera_
agustina.aylen_
agusledesmaa
__agusbelen__
brisaaguss_
agustinaahierschfeld
_aguscoria_
agustina_diagostino
agusalvarr
agustinadeniseeee
agustinagrilli_
agusredes_
agustinanicole21
camilaribaas
camilaserrano500
camila_ortizz
camila.sosa__._
camikleone
cammi_saavedra
camila_segoviaa
camila.yavi
camila.rodriiguez
camiii_pacheco
cami_canete
lanegra_eren
_camila.rocio
camila.miranda.17
camireyyes
caamilopez_
_cachetonna
sandacamila
cam.aguirre
camirigaray
camitanusi
camila_cozzolino
camiregiss_
cami_muscia
cami_callegaris
camilagirymorrn
margln_
martina_carpita
sofii.martinezzz23
angelica_martinez187
martina
marbentancourt_
martuvec
m.martinag
martiinapodesta
mar_sicora04
_.martina
martina_rosa22
martistwrt
martugalindez_
martuu.x
martinaordonezz
martinadelgadomieres
martuliber
romimartinez04
martinaayelen__
marttuprieto
maarsanchez1
martu.cam
martinasanchez1773
valelaclau
florenciia.coria
anto_pastranaa
1908larissa3
drama.queen.babyy
ana_farabollini
belen_espinosa_03
giulidellarosa
candela__pm
akkm.ore19
sw.paladar
bermudez_guada
fofi.28
miluvargass
naiarayazminn
lola_catalano_
mar.encina
deolinda3191
chiki_nasty
dannaelyn
lau4____
victoria.fontana
bel.antonella
___tiziaana22___
cele18735
mollobel
imeliberardi01
mariaelenastasiuk_
iris_padron22
zairabeccari
agusxdominguez
bandatoxica
_piba_intensa_
vero.berrospe222
melisabarlesi
tatiana15vargas
juanilovesu
abiigail.medina
dani_pavon27
rulito_yoa
fannytorress22
marteganimilagros
anto_mansi_
vipeza1902
marits_ok
tthanya.n.n
miavelazquez618
nahiaravanina
maaitealvarenga
yaninaareias
jaquelin_mallea
naara_leao_perez
luce_mendieta
sabimerenda
leila.tevez
gabiimontenegro98
loo.h_18
ugo.na_
macarena_eb
nahir.kujar17
mili_cristal24
micaelaledesma17
_alevarela.ok
sara_79632
mayle_085
rociojos1
milagros.gallardo1
jaquelin.e23
alme0819
sofi971
ludmibenitez__
nahibaudraco
antoyks
sofidenise_10
mmilatejera_
oli_romero3
zamtormakh_
micaela_arias0
moreereyes_
andregriix.e_la.07
colo_vazquez_
frida_jmt
dai_flor87
ddoloresveron
delfinaailen12
ludm.i1926
isa_vozzi._
anntoo06
moreyasmin99
mariiapatroon
celesvazqueez
maia_diaz.ok8
_val3nn.00
restelligabriela81
i_sophitaa._
_ludmiibeleen_
abigailolivera2009
lupecalderon_
jujusaldana
tiarabusta
nahir_fernandez1
ren4cpam
cami_1336
aluhe.rm
luluulopez__
malenagulich
ailenlatt
innnblckwllx
mendozaa17_
zaza_okk
_nadiemejorqueyo
celes.magaa
kalibusines.s
laurpr20
laranerea_
_ailufernandez_
melanysalinas_
x_nyarlath0tep_x
ludmilaperez943
milagros_martina17
caaam.ifc
solsscito_
milagros_lugo21
moro.pr
_paulamicaela21
tatiana.04_
iaruu13_
x1menaabigail
zoealva__
morenaabigail__
jjulietamora
ppurpurinee
solange._018
floor_veraaa
martu_lencinaa
_ppaazz01
martuu.medinna
sharon.gonzaleez
bren__ruiz_
tatianaamicaelaa
_nereeagmzz
__luciiana2005_
camii.yers
naaaisilvaa
zaiiraa_loanaa
lunaeche
muruaguada98
g.briiisa
ailu_.correg.18
maia_baezz
valenzirulia
pipisaltarelli
ahsvals
meeel.castro1
kiarajasmine_sl
whossmaca
azuuzambra`

// ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
// ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

const usersToFollow = data.split("\n");
function main() {
        // let usersToFollow = data.split("\n");
        // for (let x in usersToFollow) {
        //    usersToFollow[x] = usersToFollow[x].replaceAll(" ", "")
        //    usersToFollow[x] = usersToFollow[x].replaceAll("%20", "")
        // }
        let date = new Date;
        let hours = date.getHours();
        let minutes = date.getMinutes();
        let seconds = date.getSeconds();
        let currentUserPage = getCurrentURL().replaceAll("https://www.instagram.com/", "").replaceAll("/", "").replaceAll(" ", "").replaceAll("%20", "");
        // let followElement = findNodeByInnerHTML(document.querySelectorAll('div'), 'Follow');
        // followElement.click();
        // let currentTime = hours + ":" + minutes + ":" + seconds;
        // console.log("currentUserPage = " + currentUserPage + " || currentTime = " + currentTime)
        if (seconds == 0 && (minutes == 0 || minutes == 00)) {
            if (usersToFollow.includes(currentUserPage) == false) {
                // console.log("• Redirigiendo en 5 segundos ...");
                setTimeout(function() {
                    // console.log("• Redirigiendo");
                    window.location.href = "https://www.instagram.com/" + usersToFollow[0];
                }, 5000);
            }
            for (let i in usersToFollow) {
                let currentUser = usersToFollow[i];
                if (currentUserPage == currentUser) {
                    // console.log("• Redirigiendo en 5 segundos ...");
                    setTimeout(function() {
                        // console.log("• Redirigiendo");
                        window.location.href = "https://www.instagram.com/" + usersToFollow[parseInt(i) + 1];
                    }, 5000);
                }
            }
        }
}

setInterval(main, 1000);
//main();
// console.log("• Followeando en 45 ...");
setTimeout(function() {
    // console.log("• Followeando");
    let xpath = "//div[text()='Follow']";
    let matchingElement = document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
    matchingElement.click();
}, 45000); // 5000 no alcanza
